### ISSUE TITLE
Ouster lidar os1 64 

### ISSUE THREAD

**Issue by islamtalha01** [chinitaberrio/cam_lidar_calibration#1]
Can this package be used for calibration of ouster os2 64 and Ip camera with this package? if it is possible then kindly guide me to complete the procedure I am doing as the research intern at NUST Pakistan. Kindly help me to achieve this task.

**Comment by chinitaberrio** [comment]
We haven't tested it yet on Ouster lidars, I presume it should perform well if you have all the required information. Please use this package: https://gitlab.acfr.usyd.edu.au/its/cam_lidar_calibration 
All the instructions are in the readme file.
